In [1]:
import numpy as np


In [28]:
# 3 order tensor
A = np.array([[[10,20,30],[40,50,60],[70,80,90]],[[11,21,31],[41,51,61],[71,81,91]],[[12,22,32],[42,52,62],[72,82,92]],[[13,23,33],[43,53,63],[73,83,93]]])

In [29]:
print(A)
print(A.shape)

[[[10 20 30]
  [40 50 60]
  [70 80 90]]

 [[11 21 31]
  [41 51 61]
  [71 81 91]]

 [[12 22 32]
  [42 52 62]
  [72 82 92]]

 [[13 23 33]
  [43 53 63]
  [73 83 93]]]
(4, 3, 3)


In [32]:
C = A[1,:,:]

In [33]:
B = A 
D = np.array([A,B])

In [26]:
type(D)

numpy.ndarray

In [27]:
D.shape

(2, 4, 3, 3)

In [34]:
C.shape

(3, 3)

In [35]:
C.reshape(3,3,1)

array([[[11],
        [21],
        [31]],

       [[41],
        [51],
        [61]],

       [[71],
        [81],
        [91]]])